/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_ac_kaist_se_deltatable_DeltaTableEntryIterator */

#ifndef _Included_kr_ac_kaist_se_deltatable_DeltaTableEntryIterator
#define _Included_kr_ac_kaist_se_deltatable_DeltaTableEntryIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaTableEntryIterator
 * Method:    _hasNext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kr_ac_kaist_se_deltatable_DeltaTableEntryIterator__1hasNext
  (JNIEnv *, jobject);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaTableEntryIterator
 * Method:    _next
 * Signature: (Lkr/ac/kaist/se/deltatable/DeltaTableEntryIterator/DeltaTableEntry;)I
 */
JNIEXPORT jint JNICALL Java_kr_ac_kaist_se_deltatable_DeltaTableEntryIterator__1next
  (JNIEnv *, jobject, jobject);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaTableEntryIterator
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_ac_kaist_se_deltatable_DeltaTableEntryIterator_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
