/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_ac_kaist_se_deltatable_DeltaTableInfo */

#ifndef _Included_kr_ac_kaist_se_deltatable_DeltaTableInfo
#define _Included_kr_ac_kaist_se_deltatable_DeltaTableInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaTableInfo
 * Method:    initialize
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_kr_ac_kaist_se_deltatable_DeltaTableInfo_initialize
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaTableInfo
 * Method:    addLink
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_kr_ac_kaist_se_deltatable_DeltaTableInfo_addLink
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaTableInfo
 * Method:    addMembership
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_kr_ac_kaist_se_deltatable_DeltaTableInfo_addMembership
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaTableInfo
 * Method:    possibleMoveMethod
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_kr_ac_kaist_se_deltatable_DeltaTableInfo_possibleMoveMethod
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaTableInfo
 * Method:    getClassCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kr_ac_kaist_se_deltatable_DeltaTableInfo_getClassCount
  (JNIEnv *, jobject);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaTableInfo
 * Method:    getEntityCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kr_ac_kaist_se_deltatable_DeltaTableInfo_getEntityCount
  (JNIEnv *, jobject);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaTableInfo
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_ac_kaist_se_deltatable_DeltaTableInfo_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
