/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_ac_kaist_se_deltatable_DeltaValueEngine */

#ifndef _Included_kr_ac_kaist_se_deltatable_DeltaValueEngine
#define _Included_kr_ac_kaist_se_deltatable_DeltaValueEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaValueEngine
 * Method:    initialize
 * Signature: (Lkr/ac/kaist/se/deltatable/DeltaTableInfo;)V
 */
JNIEXPORT void JNICALL Java_kr_ac_kaist_se_deltatable_DeltaValueEngine_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaValueEngine
 * Method:    move
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_kr_ac_kaist_se_deltatable_DeltaValueEngine_move
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaValueEngine
 * Method:    createClass
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kr_ac_kaist_se_deltatable_DeltaValueEngine_createClass
  (JNIEnv *, jobject);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaValueEngine
 * Method:    getDValue
 * Signature: (III)F
 */
JNIEXPORT jfloat JNICALL Java_kr_ac_kaist_se_deltatable_DeltaValueEngine_getDValue
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaValueEngine
 * Method:    getExtractClassDValue
 * Signature: (I[I)F
 */
JNIEXPORT jfloat JNICALL Java_kr_ac_kaist_se_deltatable_DeltaValueEngine_getExtractClassDValue
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     kr_ac_kaist_se_deltatable_DeltaValueEngine
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_ac_kaist_se_deltatable_DeltaValueEngine_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
