/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_ac_kaist_se_deltatable_DeltaTableEntryIterator_DeltaTableEntry */

#ifndef _Included_kr_ac_kaist_se_deltatable_DeltaTableEntryIterator_DeltaTableEntry
#define _Included_kr_ac_kaist_se_deltatable_DeltaTableEntryIterator_DeltaTableEntry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
